const fs = require('fs');
const exercises = require('../src/data/exercises.json');

const BASE_YOGA = {category:"cooldown",type:"flexibility",safetyTier:"green",source:"Yoga Alliance, Evidence-based yoga therapy",lastReviewed:"2025-01-01",
  phaseParams:{"1":{sets:"1",reps:"30-60s hold",tempo:"Static hold",rest:"0s",intensity:"RPE 2-3"}},
  contraindications:{injuries:[],conditions:[],movements_to_avoid:[],severity_gate:{lower_back:5,knee:5,shoulder:5}},
  prerequisites:{minCompletedSessions:0,requiredExercisesMastered:[],requiredCapabilities:[],minPhase:1,maxInjurySeverity:{lower_back:5,knee:5,shoulder:5},painFreeROM:[],notes:""},
  substitutions:{home:null,outdoor:null,injury_lower_back:null,injury_knee:null,injury_shoulder:null,no_equipment:null},
  imageUrl:null,imageUrl2:null,equipmentRequired:["mat"],locationCompatible:["gym","home","outdoor"],jointsInvolved:["spine","hip"]};

const beginner = [
  {id:"yoga_child_pose",name:"Child's Pose",emoji:"🧒",bodyPart:"back",movementPattern:"static_stretch",primaryMuscles:["Erector Spinae","Lats"],secondaryMuscles:["Glutes","Shoulders"],difficultyLevel:1,weekMinimum:1,phaseEligibility:[1,2,3,4,5],
    steps:["Kneel, sit hips back toward heels.","Walk hands forward, forehead to floor.","Breathe into lower back — 5 deep breaths."],formCues:["✅ Hips toward heels","✅ Forehead rests on floor","✅ Arms extended or at sides"],commonMistakes:["❌ Not sitting back","❌ Holding breath"],coreBracing:"ZERO.",breathing:{inhale:"4",hold:"0",exhale:"6",pattern:"Belly breathing into lower back"},injuryNotes:{lower_back:"One of the BEST positions for decompression.",knee:"Rolled towel behind knees if uncomfortable.",shoulder:"Arms at sides if overhead bothers shoulder."},purpose:"Spinal decompression and parasympathetic activation.",whyForYou:"Your back's reset button. Use daily.",proTip:"This is a resting pose — stay as long as you want.",tags:["yoga","beginner","back","stretch","decompression"],_yogaLevel:"beginner",_yogaTarget:"back"},
  {id:"yoga_cat_cow",name:"Cat-Cow Flow (Yoga)",emoji:"🐱",bodyPart:"back",movementPattern:"mobility",primaryMuscles:["Erector Spinae"],secondaryMuscles:["TVA","Multifidus"],difficultyLevel:1,weekMinimum:1,phaseEligibility:[1,2,3,4,5],
    steps:["All fours. Cow: inhale, drop belly, lift chest.","Cat: exhale, round spine, tuck chin.","Flow with breath — one transition per breath."],formCues:["✅ Initiate from pelvis","✅ One breath per transition","✅ Feel each vertebra"],commonMistakes:["❌ Jerking between positions","❌ Only moving head"],coreBracing:"LIGHT (20%).",breathing:{inhale:"3",hold:"0",exhale:"3",pattern:"Inhale to cow, exhale to cat"},injuryNotes:{lower_back:"Gentle segmental motion. Reduce range if sharp pain.",knee:"Pad knees.",shoulder:"Fists if wrists hurt."},purpose:"Spinal segmental mobility with breath.",whyForYou:"Warms every vertebral segment before training.",proTip:"Close eyes — feel the wave through your spine.",tags:["yoga","beginner","back","mobility","spine"],_yogaLevel:"beginner",_yogaTarget:"back"},
  {id:"yoga_supine_twist",name:"Supine Twist",emoji:"🌀",bodyPart:"back",movementPattern:"rotation",primaryMuscles:["Obliques","Thoracic Rotators"],secondaryMuscles:["Glutes","Piriformis"],difficultyLevel:1,weekMinimum:1,phaseEligibility:[1,2,3,4,5],
    steps:["Lie on back. Knees to chest.","Let both knees fall to one side.","Arms in T. Look opposite direction. Hold 30s.","Switch sides."],formCues:["✅ Opposite shoulder stays down","✅ Knees together","✅ Let gravity do the work"],commonMistakes:["❌ Forcing knees to floor","❌ Shoulder lifting"],coreBracing:"ZERO.",breathing:{inhale:"4",hold:"0",exhale:"6",pattern:"Exhale to sink deeper"},injuryNotes:{lower_back:"Gentle supported rotation. Stop if sharp pain.",knee:"Pillow between knees.",shoulder:"T position — bend elbow if shoulder limited."},purpose:"Gentle thoracic rotation and spinal release.",whyForYou:"End-of-session spinal release. Safe and effective.",proTip:"5 slow breaths each side. This is medicine.",tags:["yoga","beginner","back","rotation"],_yogaLevel:"beginner",_yogaTarget:"back"},
  {id:"yoga_legs_wall",name:"Legs Up the Wall",emoji:"🦵",bodyPart:"legs",movementPattern:"static_stretch",primaryMuscles:["Hamstrings"],secondaryMuscles:["Calves","Lower Back"],difficultyLevel:1,weekMinimum:1,phaseEligibility:[1,2,3,4,5],
    steps:["Sit sideways against wall. Swing legs up.","Scoot hips to wall. Legs straight up.","Arms at sides or on belly. Breathe. 3-5 min."],formCues:["✅ Hips close to wall","✅ Legs straight (slight bend OK)","✅ Completely relaxed"],commonMistakes:["❌ Hips too far from wall","❌ Not staying long enough"],coreBracing:"ZERO.",breathing:{inhale:"4",hold:"0",exhale:"6",pattern:"Slow diaphragmatic"},injuryNotes:{lower_back:"Decompresses lumbar. Excellent for back.",knee:"Straight legs — slight bend if needed.",shoulder:"Arms wherever comfortable."},purpose:"Circulation, gentle hamstring stretch, parasympathetic activation.",whyForYou:"The single best restorative pose. Try it daily.",proTip:"Set a timer for 5 min. Close your eyes. This changes everything.",tags:["yoga","beginner","legs","restorative"],_yogaLevel:"beginner",_yogaTarget:"legs"},
  {id:"yoga_seated_fold",name:"Seated Forward Fold",emoji:"🙇",bodyPart:"back",movementPattern:"static_stretch",primaryMuscles:["Hamstrings","Erector Spinae"],secondaryMuscles:["Calves"],difficultyLevel:1,weekMinimum:1,phaseEligibility:[1,2,3,4,5],
    steps:["Sit with legs extended. Sit tall first.","Hinge from hips — fold forward.","Hold wherever you reach. 30s."],formCues:["✅ Hinge from HIPS","✅ Don't round to reach further","✅ 6/10 stretch"],commonMistakes:["❌ Rounding back aggressively","❌ Bouncing"],coreBracing:"ZERO.",breathing:{inhale:"3",hold:"0",exhale:"5",pattern:"Exhale to fold deeper"},injuryNotes:{lower_back:"Hinge from hips. Stop if back pain.",knee:"Slight bend OK.",shoulder:"No impact."},purpose:"Posterior chain stretch and calming.",whyForYou:"Calming pose. Stretches hamstrings without back risk when done correctly.",proTip:"Bend knees slightly if hamstrings are tight. The hip hinge matters more than reaching toes.",tags:["yoga","beginner","back","hamstrings"],_yogaLevel:"beginner",_yogaTarget:"back"},
  {id:"yoga_bridge",name:"Bridge Pose",emoji:"🌉",bodyPart:"glutes",movementPattern:"hinge",primaryMuscles:["Glutes","Hamstrings"],secondaryMuscles:["Core","Hip Flexors stretch"],difficultyLevel:1,weekMinimum:1,phaseEligibility:[1,2,3,4,5],
    steps:["Lie on back. Knees bent, feet hip-width.","Press through heels. Lift hips.","Hold at top — squeeze glutes. 30s."],formCues:["✅ Drive through heels","✅ Squeeze glutes at top","✅ No hyperextending"],commonMistakes:["❌ Hyperextending back","❌ Pushing through toes"],coreBracing:"MODERATE (30%).",breathing:{inhale:"3",hold:"0",exhale:"3",pattern:"Breathe at top"},injuryNotes:{lower_back:"No hyperextension. Glutes should drive, not back.",knee:"Adjust foot position for comfort.",shoulder:"No impact."},purpose:"Gentle glute activation + hip flexor opening.",whyForYou:"Opens hip flexors that tighten from sitting.",proTip:"Place a block between knees to activate glute med simultaneously.",tags:["yoga","beginner","glutes","hips"],_yogaLevel:"beginner",_yogaTarget:"hips"},
  {id:"yoga_reclined_butterfly",name:"Reclined Butterfly",emoji:"🦋",bodyPart:"hips",movementPattern:"static_stretch",primaryMuscles:["Adductors","Hip External Rotators"],secondaryMuscles:["Groin"],difficultyLevel:1,weekMinimum:1,phaseEligibility:[1,2,3,4,5],
    steps:["Lie on back. Soles together, knees fall open.","Arms at sides. Breathe. 2-3 min.","Blocks under knees if too intense."],formCues:["✅ Let gravity open hips","✅ Support knees if needed","✅ Completely relaxed"],commonMistakes:["❌ Forcing knees down","❌ Not using props"],coreBracing:"ZERO.",breathing:{inhale:"4",hold:"0",exhale:"6",pattern:"Slow belly breathing"},injuryNotes:{lower_back:"Supine — supported.",knee:"Props under knees.",shoulder:"No impact."},purpose:"Passive hip opener and groin stretch.",whyForYou:"Opens hips without any effort. Restorative.",proTip:"Props make this sustainable for longer holds. Don't tough it out — use blocks.",tags:["yoga","beginner","hips","restorative"],_yogaLevel:"beginner",_yogaTarget:"hips"},
  {id:"yoga_savasana",name:"Corpse Pose (Savasana)",emoji:"😌",bodyPart:"full_body",movementPattern:"breathing",primaryMuscles:["Diaphragm"],secondaryMuscles:["Parasympathetic NS"],difficultyLevel:1,weekMinimum:1,phaseEligibility:[1,2,3,4,5],
    steps:["Lie flat. Arms at sides, palms up.","Close eyes. Scan body — release tension.","Breathe naturally. Stay 3-5 min."],formCues:["✅ Palms UP","✅ Feet fall naturally open","✅ Jaw relaxed, tongue off roof"],commonMistakes:["❌ Skipping this pose","❌ Not staying long enough"],coreBracing:"ZERO.",breathing:{inhale:"Natural",hold:"0",exhale:"Natural",pattern:"Natural uncontrolled breathing"},injuryNotes:{lower_back:"Bolster under knees if needed.",knee:"No impact.",shoulder:"No impact."},purpose:"Full body relaxation and nervous system reset.",whyForYou:"The most important pose. Integration of everything you just did.",proTip:"This is NOT optional. It's where the benefits integrate. Stay 5 min.",tags:["yoga","beginner","full_body","restorative","breathing"],_yogaLevel:"beginner",_yogaTarget:"full_body"},
  {id:"yoga_knees_chest",name:"Knees to Chest",emoji:"🤱",bodyPart:"back",movementPattern:"static_stretch",primaryMuscles:["Lower Back","Glutes"],secondaryMuscles:["Hips"],difficultyLevel:1,weekMinimum:1,phaseEligibility:[1,2,3,4,5],
    steps:["Lie on back. Pull both knees to chest.","Wrap arms around shins.","Rock gently side to side. 30s."],formCues:["✅ Head stays on floor","✅ Gentle rocking OK","✅ Pull with arms, not abs"],commonMistakes:["❌ Straining neck up","❌ Pulling too aggressively"],coreBracing:"ZERO.",breathing:{inhale:"3",hold:"0",exhale:"5",pattern:"Exhale to pull closer"},injuryNotes:{lower_back:"Gentle lumbar flexion. Good for most backs.",knee:"Hands behind knees if knee is sensitive.",shoulder:"No impact."},purpose:"Lower back relief and gentle hip flexion.",whyForYou:"Quick back relief pose. Do anytime your back feels tight.",proTip:"The gentle rocking massages the sacrum and SI joint.",tags:["yoga","beginner","back","relief"],_yogaLevel:"beginner",_yogaTarget:"back"},
  {id:"yoga_thread_needle",name:"Thread the Needle",emoji:"🪡",bodyPart:"shoulders",movementPattern:"rotation",primaryMuscles:["Thoracic Rotators","Rhomboids"],secondaryMuscles:["Posterior Deltoid"],difficultyLevel:1,weekMinimum:1,phaseEligibility:[1,2,3,4,5],
    steps:["All fours. Thread right arm under left — shoulder to floor.","Hold 5 breaths. Open right arm to ceiling.","Return. Repeat other side."],formCues:["✅ Hips stay over knees","✅ Feel thoracic rotation","✅ Both thread and open phases"],commonMistakes:["❌ Hips shifting back","❌ Only threading, not opening"],coreBracing:"ZERO.",breathing:{inhale:"3",hold:"0",exhale:"4",pattern:"Exhale to thread, inhale to open"},injuryNotes:{lower_back:"Thoracic rotation — protects lumbar.",knee:"Pad knees.",shoulder:"Reduce depth if shoulder catches."},purpose:"Thoracic rotation + shoulder stretch.",whyForYou:"Opens your thoracic spine so your lumbar doesn't have to rotate.",proTip:"The OPEN phase (arm to ceiling) is as important as the thread.",tags:["yoga","beginner","shoulders","thoracic","rotation"],_yogaLevel:"beginner",_yogaTarget:"shoulders"},
];

const intermediate = [
  {id:"yoga_down_dog",name:"Downward Dog",emoji:"🐕",bodyPart:"full_body",movementPattern:"static_stretch",primaryMuscles:["Hamstrings","Calves","Lats"],secondaryMuscles:["Shoulders","Core"],difficultyLevel:2,weekMinimum:2,phaseEligibility:[1,2,3,4,5],
    steps:["From plank, push hips UP and BACK.","Hands shoulder-width, feet hip-width.","Press heels toward floor. Hold 30s."],formCues:["✅ Straight spine — bend knees if needed","✅ Push floor away","✅ Ears between biceps"],commonMistakes:["❌ Rounding upper back","❌ Locked knees with rounded back"],coreBracing:"MODERATE (30%).",breathing:{inhale:"3",hold:"0",exhale:"4",pattern:"Continuous breathing"},injuryNotes:{lower_back:"Bend knees to keep spine straight.",knee:"Soft knee bend.",shoulder:"Weight-bearing — shoulder severity ≤3."},purpose:"Full posterior chain stretch + shoulder stability.",whyForYou:"The most complete single stretch. Works everything.",proTip:"Bend your knees as much as needed — straight spine matters more than straight legs.",tags:["yoga","intermediate","full_body","stretch"],_yogaLevel:"intermediate",_yogaTarget:"full_body",
    contraindications:{injuries:[],conditions:[],movements_to_avoid:[],severity_gate:{lower_back:4,knee:4,shoulder:3}}},
  {id:"yoga_warrior1",name:"Warrior I",emoji:"⚔️",bodyPart:"hips",movementPattern:"lunge",primaryMuscles:["Hip Flexors","Quads"],secondaryMuscles:["Core","Shoulders"],difficultyLevel:2,weekMinimum:2,phaseEligibility:[1,2,3,4,5],
    steps:["Step one foot back. Front knee at 90°.","Back foot angled 45°. Square hips forward.","Arms overhead. Hold 30s each side."],formCues:["✅ Front knee over ankle","✅ Hips square forward","✅ Ribs down — no arching"],commonMistakes:["❌ Knee past toes","❌ Back foot flat causing hip rotation"],coreBracing:"MODERATE.",breathing:{inhale:"3",hold:"0",exhale:"3",pattern:"Continuous with effort"},injuryNotes:{lower_back:"Keep ribs down — no arching.",knee:"Front knee at 90° max.",shoulder:"Arms overhead — severity ≤3."},purpose:"Hip flexor stretch + balance + leg endurance.",whyForYou:"Functional lunge position with hip flexor opening.",proTip:"The back hip flexor is where the stretch should be.",tags:["yoga","intermediate","hips","balance","lunge"],_yogaLevel:"intermediate",_yogaTarget:"hips"},
  {id:"yoga_warrior2",name:"Warrior II",emoji:"⚔️",bodyPart:"hips",movementPattern:"lunge",primaryMuscles:["Quads","Hip Abductors"],secondaryMuscles:["Core","Shoulders"],difficultyLevel:2,weekMinimum:2,phaseEligibility:[1,2,3,4,5],
    steps:["Wide stance. Front foot forward, back foot perpendicular.","Front knee bends to 90°.","Arms wide at shoulder height. Gaze over front hand. Hold 30s."],formCues:["✅ Front knee over ankle","✅ Shoulders over hips","✅ Arms active — reaching"],commonMistakes:["❌ Leaning forward","❌ Knee collapsing in"],coreBracing:"MODERATE.",breathing:{inhale:"3",hold:"0",exhale:"3",pattern:"Steady breathing"},injuryNotes:{lower_back:"Neutral spine.",knee:"Front knee tracks over toes.",shoulder:"Arms at shoulder height — manageable for most."},purpose:"Hip opener + leg endurance + focus.",whyForYou:"Builds leg endurance and hip stability in open position.",proTip:"Sink lower for more challenge. Rise up when fatigued.",tags:["yoga","intermediate","hips","legs","balance"],_yogaLevel:"intermediate",_yogaTarget:"hips"},
  {id:"yoga_triangle",name:"Triangle Pose",emoji:"🔺",bodyPart:"full_body",movementPattern:"static_stretch",primaryMuscles:["Obliques","Hamstrings","IT Band"],secondaryMuscles:["Adductors","Intercostals"],difficultyLevel:2,weekMinimum:3,phaseEligibility:[1,2,3,4,5],
    steps:["Wide stance like Warrior II but front leg straight.","Hinge at hip — reach front hand to shin/floor.","Top arm reaches to ceiling. Hold 30s."],formCues:["✅ Hinge at hip, not waist","✅ Both sides of torso long","✅ Stack shoulders"],commonMistakes:["❌ Rounding to reach floor","❌ Collapsing chest"],coreBracing:"LIGHT.",breathing:{inhale:"3",hold:"0",exhale:"4",pattern:"Breathe into top side"},injuryNotes:{lower_back:"Hinge from hip — no spinal rounding.",knee:"Front leg straight but not locked.",shoulder:"Top arm up — modify if limited."},purpose:"Lateral chain stretch — obliques, IT band, intercostals.",whyForYou:"Stretches the lateral line that rarely gets attention.",proTip:"Use a block under bottom hand — makes the pose accessible and safe.",tags:["yoga","intermediate","full_body","lateral"],_yogaLevel:"intermediate",_yogaTarget:"full_body"},
  {id:"yoga_pigeon_mod",name:"Pigeon Pose (Modified with Props)",emoji:"🐦",bodyPart:"hips",movementPattern:"static_stretch",primaryMuscles:["Piriformis","Glute Med","Hip ER"],secondaryMuscles:["Hip Flexors"],difficultyLevel:2,weekMinimum:3,phaseEligibility:[1,2,3,4,5],
    steps:["From all fours, slide right knee forward.","Back leg extends straight. Block under front hip.","Fold forward as tolerated. Hold 60s each side."],formCues:["✅ Block under hip for support","✅ Hips stay square","✅ Fold only as deep as comfortable"],commonMistakes:["❌ No block (hip drops)","❌ Forcing depth"],coreBracing:"ZERO.",breathing:{inhale:"4",hold:"0",exhale:"6",pattern:"Long exhales to release"},injuryNotes:{lower_back:"Fold only within comfort.",knee:"Front shin angle adjustable. Stop if knee pain.",shoulder:"No impact."},purpose:"Deep hip external rotation stretch — modified for safety.",whyForYou:"Opens the deep hip rotators that compress nerves when tight.",proTip:"ALWAYS use a block. It keeps hips level and makes the pose sustainable.",tags:["yoga","intermediate","hips","hip_opener"],_yogaLevel:"intermediate",_yogaTarget:"hips",
    contraindications:{injuries:[],conditions:["hip_labral_tear"],movements_to_avoid:[],severity_gate:{lower_back:5,knee:3,shoulder:5}}},
  {id:"yoga_low_lunge",name:"Low Lunge",emoji:"🏃",bodyPart:"hips",movementPattern:"lunge",primaryMuscles:["Iliopsoas","Rectus Femoris"],secondaryMuscles:["Quads"],difficultyLevel:2,weekMinimum:2,phaseEligibility:[1,2,3,4,5],
    steps:["Step one foot forward into deep lunge. Back knee on floor.","Sink hips down and forward.","Arms overhead or on front knee. Hold 30s."],formCues:["✅ Hips sink forward and down","✅ Back knee padded","✅ Upright torso"],commonMistakes:["❌ Leaning forward","❌ Back knee on hard surface"],coreBracing:"LIGHT.",breathing:{inhale:"3",hold:"0",exhale:"5",pattern:"Exhale to sink deeper"},injuryNotes:{lower_back:"Keep torso upright.",knee:"Back knee padded. Front knee over ankle.",shoulder:"Arms overhead optional."},purpose:"Deep hip flexor stretch.",whyForYou:"Opens the hip flexors shortened by sitting all day.",proTip:"Add a gentle backbend at the top for extra hip flexor + ab stretch.",tags:["yoga","intermediate","hips","hip_flexor"],_yogaLevel:"intermediate",_yogaTarget:"hips"},
  {id:"yoga_cobra",name:"Cobra Pose",emoji:"🐍",bodyPart:"back",movementPattern:"mobility",primaryMuscles:["Erector Spinae"],secondaryMuscles:["Glutes","Shoulders"],difficultyLevel:2,weekMinimum:2,phaseEligibility:[1,2,3,4,5],
    steps:["Lie face down. Hands under shoulders.","Press up — lift chest. Keep hips on floor.","Hold 15-30s. Lower slowly."],formCues:["✅ Hips stay on floor","✅ Elbows slightly bent","✅ Shoulders away from ears"],commonMistakes:["❌ Lifting hips","❌ Locking elbows"],coreBracing:"LIGHT.",breathing:{inhale:"3",hold:"5",exhale:"3",pattern:"Inhale to lift, hold, exhale to lower"},injuryNotes:{lower_back:"Similar to McKenzie press-up. Gentle extension.",knee:"No impact.",shoulder:"Moderate load. Severity ≤3."},purpose:"Gentle spinal extension — similar to McKenzie press-up.",whyForYou:"Extension opens the front of the body and benefits disc health.",proTip:"Baby cobra (elbows bent) before full cobra. Always.",tags:["yoga","intermediate","back","extension"],_yogaLevel:"intermediate",_yogaTarget:"back"},
  {id:"yoga_chair",name:"Chair Pose",emoji:"🪑",bodyPart:"legs",movementPattern:"squat",primaryMuscles:["Quadriceps","Glutes"],secondaryMuscles:["Core","Ankles"],difficultyLevel:2,weekMinimum:3,phaseEligibility:[1,2,3,4,5],
    steps:["Stand feet together. Sit hips back — like sitting in a chair.","Arms overhead or at heart. Hold 30s.","Weight in heels. Knees over toes."],formCues:["✅ Weight in heels","✅ Chest lifted","✅ Knees don't pass toes"],commonMistakes:["❌ Leaning forward","❌ Knees caving in"],coreBracing:"MODERATE.",breathing:{inhale:"3",hold:"0",exhale:"3",pattern:"Steady breathing with effort"},injuryNotes:{lower_back:"Sit back — don't arch.",knee:"Depth limited by comfort.",shoulder:"Arms overhead optional."},purpose:"Quad endurance + ankle mobility in a static hold.",whyForYou:"Builds the leg endurance your sports demand.",proTip:"The deeper you go, the harder it gets. Find YOUR depth.",tags:["yoga","intermediate","legs","squat","endurance"],_yogaLevel:"intermediate",_yogaTarget:"legs"},
];

const advanced = [
  {id:"yoga_crow",name:"Crow Pose",emoji:"🐦",bodyPart:"arms",movementPattern:"push",primaryMuscles:["Triceps","Core","Hip Flexors"],secondaryMuscles:["Shoulders","Wrists"],difficultyLevel:4,weekMinimum:12,phaseEligibility:[2,3,4,5],
    steps:["Squat. Place hands on floor shoulder-width.","Lean forward. Place knees on backs of upper arms.","Shift weight forward — feet lift off floor. Hold."],formCues:["✅ Gaze forward, not down","✅ Round upper back","✅ Engage core deeply"],commonMistakes:["❌ Looking at floor (face plant)","❌ Not rounding enough"],coreBracing:"MAXIMUM.",breathing:{inhale:"2",hold:"3",exhale:"2",pattern:"Hold breath initially, then breathe"},injuryNotes:{lower_back:"Core must be strong.",knee:"Knees on arms — no direct stress.",shoulder:"Full weight on wrists/shoulders. Severity ≤2."},purpose:"Upper body strength + core + balance integration.",whyForYou:"An advanced milestone. Requires significant core and arm strength.",proTip:"Place a pillow in front of your face. Removes the fear of falling.",tags:["yoga","advanced","arms","core","balance"],_yogaLevel:"advanced",_yogaTarget:"full_body",safetyTier:"red",
    prerequisites:{minCompletedSessions:16,requiredExercisesMastered:["stab_plank"],requiredCapabilities:["core_stability_intermediate"],minPhase:2,maxInjurySeverity:{lower_back:3,knee:5,shoulder:2},painFreeROM:[],notes:"Phase 2+, shoulder ≤2"},
    contraindications:{injuries:["labrum_tear_acute","rotator_cuff_tear_acute"],conditions:[],movements_to_avoid:["end_range_shoulder"],severity_gate:{lower_back:3,knee:5,shoulder:2}}},
  {id:"yoga_wheel",name:"Wheel Pose (Full Backbend)",emoji:"🎡",bodyPart:"back",movementPattern:"mobility",primaryMuscles:["Erector Spinae","Glutes","Shoulders"],secondaryMuscles:["Core","Hip Flexors stretch"],difficultyLevel:4,weekMinimum:16,phaseEligibility:[2,3,4,5],
    steps:["Lie on back. Hands by ears, fingers toward shoulders.","Press up into full backbend.","Hold 15-30s. Lower slowly."],formCues:["✅ Press through hands AND feet","✅ Straighten arms","✅ Push chest through arms"],commonMistakes:["❌ Elbows flaring","❌ Not enough arm strength"],coreBracing:"HIGH.",breathing:{inhale:"3",hold:"5",exhale:"3",pattern:"Breathe at top"},injuryNotes:{lower_back:"BLOCKED if back severity ≥2. Full spinal extension.",knee:"Weight-bearing through legs.",shoulder:"Full overhead. Severity ≤1."},purpose:"Full spinal extension — extreme mobility.",whyForYou:"An advanced flexibility goal. Currently blocked by back severity.",proTip:"Bridge pose first. Then bridge with head on floor. THEN wheel.",tags:["yoga","advanced","back","extension","flexibility"],_yogaLevel:"advanced",_yogaTarget:"back",safetyTier:"red",
    prerequisites:{minCompletedSessions:20,requiredExercisesMastered:[],requiredCapabilities:[],minPhase:2,maxInjurySeverity:{lower_back:1,knee:4,shoulder:1},painFreeROM:["shoulder_flexion_180"],notes:"Back severity must be ≤1"},
    contraindications:{injuries:["disc_herniation_acute","spondylolisthesis"],conditions:["spinal_stenosis"],movements_to_avoid:["axial_loading_heavy"],severity_gate:{lower_back:1,knee:4,shoulder:1}}},
  {id:"yoga_headstand_prep",name:"Headstand Prep (Wall Only)",emoji:"🤸",bodyPart:"full_body",movementPattern:"push",primaryMuscles:["Core","Shoulders","Triceps"],secondaryMuscles:["Neck","Back"],difficultyLevel:4,weekMinimum:16,phaseEligibility:[3,4,5],
    steps:["Forearms on floor, interlace fingers. Head in hands.","Walk feet in. Lift one leg at a time against wall.","Hold with wall support. Build toward freestanding."],formCues:["✅ Wall for safety","✅ Most weight on forearms, NOT head","✅ Core engaged throughout"],commonMistakes:["❌ Weight on head (dangerous)","❌ No wall (fall risk)"],coreBracing:"MAXIMUM.",breathing:{inhale:"3",hold:"0",exhale:"3",pattern:"Steady breathing"},injuryNotes:{lower_back:"Inversion — no compression.",knee:"No impact.",shoulder:"Full overhead load. BLOCKED if neck or shoulder issues."},purpose:"Inversion + core + shoulder stability.",whyForYou:"Advanced goal. Requires neck and shoulder health.",proTip:"90% of weight on forearms. Head is just a balance point, not a weight-bearing surface.",tags:["yoga","advanced","full_body","inversion"],_yogaLevel:"advanced",_yogaTarget:"full_body",safetyTier:"red",
    prerequisites:{minCompletedSessions:20,requiredExercisesMastered:[],requiredCapabilities:[],minPhase:3,maxInjurySeverity:{lower_back:2,knee:5,shoulder:1},painFreeROM:[],notes:"BLOCKED if neck/shoulder issues"},
    contraindications:{injuries:["labrum_tear_acute"],conditions:["cervical_disc_issues"],movements_to_avoid:["end_range_shoulder"],severity_gate:{lower_back:2,knee:5,shoulder:1}}},
  {id:"yoga_dancer",name:"Dancer's Pose",emoji:"💃",bodyPart:"full_body",movementPattern:"isolation",primaryMuscles:["Quads","Hip Flexors","Shoulders"],secondaryMuscles:["Balance","Core"],difficultyLevel:3,weekMinimum:8,phaseEligibility:[2,3,4,5],
    steps:["Stand on one leg. Grab opposite ankle behind you.","Lean forward slightly. Kick foot into hand.","Reach forward arm. Hold 15-30s."],formCues:["✅ Kick into hand — creates the arch","✅ Forward arm for balance","✅ Gaze at fixed point"],commonMistakes:["❌ Not kicking into hand","❌ Losing balance focus"],coreBracing:"MODERATE.",breathing:{inhale:"3",hold:"0",exhale:"3",pattern:"Steady breathing for balance"},injuryNotes:{lower_back:"Slight extension — manageable.",knee:"Requires knee flexion.",shoulder:"One arm overhead."},purpose:"Balance + quad stretch + shoulder flexibility integration.",whyForYou:"Beautiful integration of balance, flexibility, and control.",proTip:"Start with hand against wall for balance support.",tags:["yoga","advanced","full_body","balance"],_yogaLevel:"advanced",_yogaTarget:"full_body",safetyTier:"yellow",
    contraindications:{injuries:[],conditions:[],movements_to_avoid:[],severity_gate:{lower_back:3,knee:2,shoulder:3}}},
  {id:"yoga_side_plank",name:"Side Plank Pose",emoji:"📐",bodyPart:"core",movementPattern:"anti_flexion",primaryMuscles:["Obliques","Shoulders"],secondaryMuscles:["Glute Med","Core"],difficultyLevel:3,weekMinimum:6,phaseEligibility:[1,2,3,4,5],
    steps:["From plank, rotate to one side.","Stack feet or stagger. Top arm to ceiling.","Hold 15-30s each side."],formCues:["✅ Hips stay stacked","✅ Top arm reaches UP","✅ Don't let hips sag"],commonMistakes:["❌ Hips dropping","❌ Not stacking shoulders"],coreBracing:"HIGH.",breathing:{inhale:"2",hold:"0",exhale:"3",pattern:"Continuous breathing"},injuryNotes:{lower_back:"Lateral core challenge.",knee:"Stagger feet for easier balance.",shoulder:"Full load on bottom shoulder. Severity ≤3."},purpose:"Oblique strength + shoulder stability in yoga context.",whyForYou:"Combines lateral core work with shoulder stability.",proTip:"Bottom knee on floor is the regression. Build up.",tags:["yoga","advanced","core","shoulders"],_yogaLevel:"advanced",_yogaTarget:"core",
    contraindications:{injuries:[],conditions:[],movements_to_avoid:[],severity_gate:{lower_back:3,knee:5,shoulder:3}}},
];

const allYoga = [...beginner, ...intermediate, ...advanced].map(y => ({...BASE_YOGA, ...y}));
const updated = [...exercises, ...allYoga];
console.log('Added', allYoga.length, 'yoga exercises. New total:', updated.length);
console.log('  Beginner:', beginner.length, '| Intermediate:', intermediate.length, '| Advanced:', advanced.length);
fs.writeFileSync('./src/data/exercises.json', JSON.stringify(updated, null, 2));
console.log('Saved to exercises.json');
