const exercises = require('../src/data/exercises.json');
const imageDirs = require('../src/data/tmp/exercise_image_dirs.json');
const fs = require('fs');
const BASE = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/';

const MANUAL = {
  'str_glute_bridge': 'Glute_Bridge',
  'str_db_rdl': 'Romanian_Deadlift_With_Dumbbells',
  'str_trap_bar_dl_high': 'Barbell_Deadlift',
  'str_trap_bar_dl_low': 'Barbell_Deadlift',
  'str_wall_push_up': 'Pushups',
  'str_incline_push_up': 'Incline_Push-Up',
  'str_floor_push_up': 'Pushups',
  'str_landmine_press': 'Landmine_180s',
  'str_db_floor_press': 'Dumbbell_Floor_Press',
  'str_db_bench_press': 'Dumbbell_Bench_Press',
  'str_band_pull_apart': 'Band_Pull_Apart',
  'str_chest_supported_row': 'Incline_Dumbbell_Row',
  'str_sa_db_row': 'One-Arm_Dumbbell_Row',
  'str_cable_row': 'Seated_Cable_Rows',
  'str_inverted_row': 'Inverted_Row',
  'str_bw_squat': 'Bodyweight_Squat',
  'str_goblet_squat': 'Goblet_Squat',
  'str_bss_bw': 'Single_Leg_Squat',
  'str_bss_loaded': 'Single_Leg_Squat',
  'str_front_squat': 'Front_Barbell_Squat',
  'str_sl_glute_bridge': 'Single_Leg_Glute_Bridge',
  'iso_face_pulls': 'Face_Pull',
  'iso_band_ext_rotation': 'External_Rotation_with_Band',
  'iso_bicep_curl': 'Dumbbell_Bicep_Curl',
  'iso_tricep_pushdown': 'Triceps_Pushdown',
  'iso_lateral_raise': 'Side_Lateral_Raise',
  'iso_calf_raise': 'Standing_Calf_Raises',
  'stab_dead_bug': 'Dead_Bug',
  'stab_plank': 'Plank',
  'stab_side_plank': 'Side_Plank',
  'stab_bird_dog': 'Bird_Dog',
  'stab_mcgill_curl_up': 'Crunches',
  'stab_ball_squat': 'Ball_Squat',
  'bal_single_leg': 'Single_Leg_Push-off',
  'mob_cat_cow': 'Cat_Stretch',
  'mob_thoracic_rotation': 'Lying_Crossover',
  'mob_ankle_dorsiflexion': 'Ankle_Circles',
  'stretch_hamstring': 'All_Fours_Quad_Stretch_And_target_Hamstring',
  'stretch_hip_flexor': 'Kneeling_Hip_Flexor',
  'stretch_child_pose': 'Childs_Pose',
  'stretch_upper_trap': 'Upper_Back-Loss_Stretch',
  'stretch_piriformis': 'Seated_Piriformis_Stretch',
  'stretch_quad': 'Lying_Quad_Stretch',
  'stretch_adductor': 'Butterfly_Stretch',
  'stretch_standing_calf': 'Standing_Gastrocnemius_Calf_Stretch',
  'cardio_bike': 'Recumbent_Bike',
  'fr_calves': 'Calf-SMR',
  'fr_it_band': 'Iliotibial_Tract-SMR',
  'fr_adductors': 'Adductor',
  'fr_lats': 'Latissimus_Dorsi-SMR',
  'fr_quads': 'Quadriceps-SMR',
  'fr_hamstrings': 'Hamstrings-SMR',
  'fr_piriformis': 'Piriformis-SMR',
  'core_pallof_kneel': 'Pallof_Press_With_Rotation',
  'core_pallof_stand': 'Pallof_Press_With_Rotation',
  'core_pallof_split': 'Pallof_Press_With_Rotation',
  'core_ab_wheel': 'Ab_Roller',
  'carry_sa_farmer': 'Farmers_Walk',
  'carry_suitcase': 'Farmers_Walk',
  'func_farmer_carry_bilateral': 'Farmers_Walk',
  'func_bear_crawl': 'Bear_Crawl_Shoulder_Tap',
  'func_inchworm': 'Inchworm',
  'kb_goblet_squat': 'Goblet_Squat',
  'kb_swing': 'One-Arm_Kettlebell_Swings',
  'kb_sa_press': 'One-Arm_Kettlebell_Clean_and_Jerk',
  'kb_row': 'Alternating_Kettlebell_Row',
  'kb_farmer_carry': 'Farmers_Walk',
  'kb_turkish_getup': 'Turkish_Get-Up_(Kettlebell)',
  'trx_row': 'Suspended_Row',
  'trx_pushup': 'Suspended_Push-Up',
  'trx_hamstring_curl': 'Hamstring_Curl',
  'trx_face_pull': 'Face_Pull',
  'band_lat_pulldown': 'Lat_Pull-Down',
  'band_tricep_pushdown': 'Triceps_Pushdown',
  'band_hip_thrust': 'Barbell_Hip_Thrust',
  'seated_shoulder_press': 'Seated_Dumbbell_Press',
  'seated_lateral_raise': 'Seated_Side_Lateral_Raise',
  'seated_row': 'Seated_Cable_Rows',
  'seated_bicep_curl': 'Seated_Dumbbell_Curl',
  'seated_leg_ext': 'Leg_Extensions',
  'seated_chair_dips': 'Bench_Dips',
  'seated_crunch': 'Crunches',
  'dyn_arm_circles': 'Arm_Circles',
  'dyn_walking_lunges': 'Walking_Lunge',
  'sport_power_clean': 'Power_Clean',
  'sport_box_jump': 'Box_Jump_(Multiple_Response)',
  'sport_med_ball_slam': 'Medicine_Ball_Chest_Pass',
  'sport_battle_ropes': 'Battling_Ropes',
  'sport_barbell_hip_thrust': 'Barbell_Hip_Thrust',
  'outdoor_bench_stepup': 'Barbell_Step_Ups',
  'outdoor_bench_pushup': 'Incline_Push-Up',
  'outdoor_bench_dips': 'Bench_Dips',
  'outdoor_playground_pullup': 'Pullups',
  'rehab_lateral_band_walk': 'Monster_Walk',
  'corr_clamshell': 'Clam',
  'corr_monster_walk': 'Monster_Walk',
  'grip_dead_hang': 'Pullups',
  'rehab_slr': 'Lying_Leg_Raises',
  'rehab_step_down_low': 'Barbell_Step_Ups',
  'rehab_step_down_high': 'Barbell_Step_Ups',
  'corr_standing_hip_flexor_str': 'Kneeling_Hip_Flexor',
  'corr_kneeling_hip_flexor_str': 'Kneeling_Hip_Flexor',
  'corr_supine_pelvic_tilt': 'Pelvic_Tilt_Into_Bridge',
  'corr_glute_bridge_march': 'Glute_Bridge',
  'corr_side_lying_hip_abd': 'Side_Lying_Clam',
  'rehab_fire_hydrant': 'Fire_Hydrant',
  'rehab_eccentric_calf_drop': 'Standing_Calf_Raises',
  'williams_single_knee_chest': 'Knee_Tuck_Jump',
  'williams_double_knee_chest': 'Knee_Tuck_Jump',
  'aqua_squat': 'Bodyweight_Squat',
  'iso_wall_push': 'Pushups',
  'iso_squat_hold': 'Bodyweight_Squat',
  'iso_plank_variations': 'Plank',
  'bed_pelvic_tilt': 'Pelvic_Tilt_Into_Bridge',
  'bed_glute_set': 'Glute_Bridge',
  'dyn_high_knees': 'High_Knee_Jog',
  'dyn_butt_kicks': 'Butt_Kicks',
  'agil_box_drill': 'Box_Jump_(Multiple_Response)',
  'func_squat_to_stand': 'Bodyweight_Squat',
  'seated_punches': 'Jab_Cross',
  'cond_boxing_drills': 'Jab_Cross',
  'seated_hip_abd': 'Hip_Adduction',
  'stretch_lat': 'Latissimus_Dorsi-SMR',
  'stretch_glute': 'Seated_Piriformis_Stretch',
  'stretch_neck_side_bend': 'Neck_Stretch',
  'kb_deadlift': 'Kettlebell_Sumo_Deadlift_High_Pull',
  'band_squat': 'Bodyweight_Squat',
  'band_chest_press': 'Pushups',
  'band_deadlift': 'Barbell_Deadlift',
};

// Apply
let mapped = 0, unmapped = 0;
const result = exercises.map(ex => {
  const dir = MANUAL[ex.id];
  if (dir) {
    mapped++;
    return { ...ex, imageUrl: BASE + dir + '/0.jpg', imageUrl2: BASE + dir + '/1.jpg' };
  }
  unmapped++;
  return { ...ex, imageUrl: null, imageUrl2: null };
});

console.log('Mapped:', mapped, '| Unmapped:', unmapped, '| Total:', exercises.length);
fs.writeFileSync('./src/data/exercises.json', JSON.stringify(result, null, 2));
console.log('Updated exercises.json');
